
volumes:
  postgres-s-data: # Declare the named volume here
    name: postgres-s-data
    driver: local
  mongo-s-data: 
    name: mongo-s-data
    driver: local
  document-data: 
    name: document-data
    driver: local

networks:
  rempms-shared-network: # Declare the network
    driver: bridge
    
services:
  postgresqldb:
    image: 'bitnami/postgresql:17.5.0'
    container_name: 'postgresqldb'
    ports:
      - '5432:5432'
    volumes:
      - postgres-s-data:/bitnami/postgresql:rw # rw: Read-write(Default) | ro: Read-only(Safer)
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 20s
      timeout: 5s
      retries: 20
    environment:
      POSTGRESQL_USERNAME: postgres       
      POSTGRESQL_PASSWORD: rempmsprod@123  
    networks:
      - rempms-shared-network
            
  mongodb:
    image: 'mongo:8.0.9'
    container_name: 'mongodb'
    ports:
      - '27017:27017'
    volumes:
      - mongo-s-data:/data/db:rw
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ hello: 1 })"]
      interval: 20s
      timeout: 5s
      retries: 20
    networks:
      - rempms-shared-network

  rempms-rabbitmq:
    image: "rabbitmq:4-management"
    container_name: rempms-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 5s
    networks:
      - rempms-shared-network
      
  rempms-configuration-service:
    image: "maleeshasa/rempms-configuration-service:v3"
    container_name: rempms-configuration-service
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      rempms-rabbitmq:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: rempms-configuration-service
      SPRING_RABBITMQ_HOST: rempms-rabbitmq
    networks:
      - rempms-shared-network

  rempms-eureka-service:
    image: "maleeshasa/rempms-eureka-service:v3"
    container_name: rempms-eureka-service
    ports:
      - "8070:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      rempms-rabbitmq:
        condition: service_healthy
      rempms-configuration-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: rempms-eureka-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://rempms-eureka-service:8070/eureka/
      EUREKA_INSTANCE_HOSTNAME: rempms-eureka-service
      SPRING_RABBITMQ_HOST: rempms-rabbitmq
      CONFIG_SERVER_URL: http://rempms-configuration-service:8071/
    networks:
      - rempms-shared-network
      
  rempms-api-gateway-service:
    image: "maleeshasa/rempms-api-gateway-service:v3"
    container_name: rempms-api-gateway-service
    ports:
      - "8081:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      rempms-rabbitmq:
        condition: service_healthy
      rempms-eureka-service:
        condition: service_healthy
      rempms-configuration-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: rempms-api-gateway-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://rempms-eureka-service:8070/eureka/
      SPRING_RABBITMQ_HOST: rempms-rabbitmq
      CONFIG_SERVER_URL: http://rempms-configuration-service:8071/
    networks:
      - rempms-shared-network   

  pdev-user-service:
    image: "maleeshasa/pdev-user-service:v3"
    container_name: pdev-user-service
    ports:
      - "9001:8080"
    healthcheck:
      test: "curl --fail --silent localhost:9001/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      rempms-rabbitmq:
        condition: service_healthy
      rempms-eureka-service:
        condition: service_healthy
      rempms-configuration-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: pdev-user-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://rempms-eureka-service:8070/eureka/
      SPRING_RABBITMQ_HOST: rempms-rabbitmq
      POSTGRES_SERVER_ADDRESS: postgresqldb
      CONFIG_SERVER_URL: http://rempms-configuration-service:8071/
    networks:
      - rempms-shared-network

  pdev-keycloak-service:
    image: "maleeshasa/pdev-keycloak-service:v3"
    container_name: pdev-keycloak-service
    ports:
      - "8823:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8823/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      rempms-rabbitmq:
        condition: service_healthy
      rempms-eureka-service:
        condition: service_healthy
      rempms-configuration-service:
        condition: service_healthy
      postgresqldb:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: pdev-keycloak-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://rempms-eureka-service:8070/eureka/
      SPRING_RABBITMQ_HOST: rempms-rabbitmq
      POSTGRES_SERVER_ADDRESS: postgresqldb
      CONFIG_SERVER_URL: http://rempms-configuration-service:8071/
    networks:
      - rempms-shared-network

  pdev-kcs-service:
    image: "maleeshasa/pdev-kcs-service:v3"
    container_name: pdev-kcs-service
    ports:
      - "8201:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8201/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      rempms-rabbitmq:
        condition: service_healthy
      rempms-eureka-service:
        condition: service_healthy
      rempms-configuration-service:
        condition: service_healthy
      postgresqldb:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: pdev-kcs-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://rempms-eureka-service:8070/eureka/
      POSTGRES_SERVER_ADDRESS: postgresqldb
      CONFIG_SERVER_URL: http://rempms-configuration-service:8071/
    networks:
      - rempms-shared-network

  rempms-candidate-service:
    image: "maleeshasa/rempms-candidate-service:v3"
    container_name: rempms-candidate-service
    ports:
      - "8088:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8088/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      rempms-rabbitmq:
        condition: service_healthy
      rempms-eureka-service:
        condition: service_healthy
      rempms-configuration-service:
        condition: service_healthy
      postgresqldb:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: rempms-candidate-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://rempms-eureka-service:8070/eureka/
      SPRING_RABBITMQ_HOST: rempms-rabbitmq
      POSTGRES_SERVER_ADDRESS: postgresqldb
      CONFIG_SERVER_URL: http://rempms-configuration-service:8071/
    networks:
      - rempms-shared-network
      
  rempms-communication-service:
    image: "maleeshasa/rempms-communication-service:v3"
    container_name: rempms-communication-service
    ports:
      - "8083:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8083/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      rempms-rabbitmq:
        condition: service_healthy
      rempms-eureka-service:
        condition: service_healthy
      rempms-configuration-service:
        condition: service_healthy
      postgresqldb:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: rempms-communication-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://rempms-eureka-service:8070/eureka/
      SPRING_RABBITMQ_HOST: rempms-rabbitmq
      POSTGRES_SERVER_ADDRESS: postgresqldb
      CONFIG_SERVER_URL: http://rempms-configuration-service:8071/
    networks:
      - rempms-shared-network
                
  rempms-document-service:
    image: "maleeshasa/rempms-document-service:v3"
    container_name: rempms-document-service
    ports:
      - "8087:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8087/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      rempms-rabbitmq:
        condition: service_healthy
      rempms-eureka-service:
        condition: service_healthy
      rempms-configuration-service:
        condition: service_healthy
      postgresqldb:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: rempms-document-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://rempms-eureka-service:8070/eureka/
      SPRING_RABBITMQ_HOST: rempms-rabbitmq
      POSTGRES_SERVER_ADDRESS: postgresqldb
      CONFIG_SERVER_URL: http://rempms-configuration-service:8071/
    networks:
      - rempms-shared-network

  rempms-draft-service:
    image: "maleeshasa/rempms-draft-service:v3"
    container_name: rempms-draft-service
    ports:
      - "8186:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8186/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      rempms-rabbitmq:
        condition: service_healthy
      rempms-eureka-service:
        condition: service_healthy
      rempms-configuration-service:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: rempms-draft-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://rempms-eureka-service:8070/eureka/
      SPRING_RABBITMQ_HOST: rempms-rabbitmq
      MONGODB_SERVER_ADDRESS: mongodb
      CONFIG_SERVER_URL: http://rempms-configuration-service:8071/
    networks:
      - rempms-shared-network

  rempms-location-service:
    image: "maleeshasa/rempms-location-service:v3"
    container_name: rempms-location-service
    ports:
      - "8084:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8084/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      rempms-rabbitmq:
        condition: service_healthy
      rempms-eureka-service:
        condition: service_healthy
      rempms-configuration-service:
        condition: service_healthy
      postgresqldb:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: rempms-location-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://rempms-eureka-service:8070/eureka/
      SPRING_RABBITMQ_HOST: rempms-rabbitmq
      POSTGRES_SERVER_ADDRESS: postgresqldb
      CONFIG_SERVER_URL: http://rempms-configuration-service:8071/
    networks:
      - rempms-shared-network

  rempms-recruitment-service:
    image: "maleeshasa/rempms-recruitment-service:v3"
    container_name: rempms-recruitment-service
    ports:
      - "8086:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8086/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      rempms-rabbitmq:
        condition: service_healthy
      rempms-eureka-service:
        condition: service_healthy
      rempms-configuration-service:
        condition: service_healthy
      postgresqldb:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: rempms-recruitment-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://rempms-eureka-service:8070/eureka/
      SPRING_RABBITMQ_HOST: rempms-rabbitmq
      POSTGRES_SERVER_ADDRESS: postgresqldb
      CONFIG_SERVER_URL: http://rempms-configuration-service:8071/
    networks:
      - rempms-shared-network
      
  rempms-candidate-fe:
    image: "maleeshasa/rempms-candidate-fe:v3"
    container_name: "rempms-candidate-fe"
    ports:
      - "8080:80"
    networks:
      - rempms-shared-network
      
  rempms-recruitment-fe:
    image: "maleeshasa/rempms-recruitment-fe:v3"
    container_name: "rempms-recruitment-fe"
    ports:
      - "8181:80"
    networks:
      - rempms-shared-network
                
  user-management-fe:
    image: "maleeshasa/user-management-fe:v3"
    container_name: "user-management-fe"
    ports:
      - "8282:80"
    networks:
      - rempms-shared-network
                    

    